config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "students#index"
  resources :students
  get 'download_pdf', to:  "students#download_pdf"
  # resources :students, only: [:index, :show]
  # namespace :monitors do
  #   resources  :students
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/student.rb
class Student < ApplicationRecord
# after_commit :download_pdf
after_create :send_welcome_email

has_one_attached :avatar
has_many_attached :images

scope :solve, -> (name){ where("name=?",name)}
scope :solve1, -> (name){where("name=?",name)}

def download_pdf
  puts "hiiiiiii"
  client = Student.find(1)
  puts "////////////"
  send_data generate_pdf(client),
            filename: "#{client.name}.pdf",
            type: "application/pdf"
end
private
def generate_pdf(client)
  Prawn::Document.new do
    text client.name, align: :center
    text "Address: #{client.address}"

  end.render
end


def send_welcome_email
  SendEmailsJob.perform_now(self)

  # SendEmailsJob.set(wait_until: Time.now+6).perform_later(self)
end
end

app/controllers/application_controller.rb
require "prawn"
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found
  # before_action :authenticate

  USERS = { "lifo" => "world" }

  def pdf_test(st)
    require "prawn"
    Prawn::Document.generate("#{st.name}.pdf") do
    text "Hello World!"
    end
  end


  private
    def require_login
      http_basic_authenticate_with name: "humbaba", password: "5baa61e4"
    end
    def generate_pdf(student)
      Prawn::Document.new do
        text student.name, align: :center
        text "Address: #{student.address}"
        text "Name: #{student.name}"
      end.render
    end

    def authenticate
      authenticate_or_request_with_http_digest do |username|
        USERS[username]
      end
    end
    def record_not_found
      render plain: "404 Not Found", status: 404
    end
end

app/controllers/monitors/students_controller.rb
class Admin::StudentsController < ApplicationController
end

app/controllers/students_controller.rb
require "prawn"
class StudentsController < ApplicationController
  before_action :print_display_message

  def index
    @students=Student.all
  end

  def show
    # @student = Student.find_by(id:params[:id],name:params[:name])
    @student=Student.find(params[:id])
  end

  def new
    @student = Student.new
  end

  def create
  #  / @student=Student.new(name:params[:student][:name],address: params[:student][:address])
    @student=Student.new(student_params)
    if @student.save
      # CrudNotificationMailer.create_notification(@student).deliver_now

      redirect_to @student
      # head :ok
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])

    if @student.update(student_params)
      redirect_to @student
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def print_display_message
    puts "i am called"
  end

  private
    def student_params
      params.require(:student).permit(:name, :address,:email,:avatar,images: [])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%=form_with model: @student do |form|%>
  <div>
    <%=form.label :name%><br>
    <%=form.text_field :name %><br>
  </div>
  <br>
  <div>
    <%=form.label :address%><br>
    <%=form.text_field :address %><br>
  </div>
  <br>
  <div>
    <%=form.label :email%><br>
    <%=form.email_field :email %><br>
  </div>
 
  <br>
   <div>
    <%=form.label :avatar%><br>
    <%=form.file_field :avatar %><br>
  </div>
  <br>
  <div>
    <%=form.label :images %><br>
    <%=form.file_field :images, multiple: true %><br>
  </div>
  <br>
   <div>
   
    <%=form.submit "submit"%><br>
  </div>
<%end%>

app/views/students/edit.html.erb
<h1>edit</h1>
name is:
<%=@student.name%>

app/views/students/index.html.erb
<h1>Welcome students</h1>
<%# <%= render "" %>
<div>
  <ul>
  <%@students.each do |s|%>
   <li> <%= s.name%></li>
    <%# <%=link_to "edit", edit_student_path(s)%> 
  <%end%>
  </ul>
</div>


<%=link_to "new student","/students/new"%>

app/views/students/new.html.erb
<h1>new</h1>
<%=render "form" ,student:@student%>

app/views/students/show.html.erb
<h1>show</h1>

<h4>Name :<%= @student.name%></h4>
<h4>Address : <%= @student.address%> </h4>
<h4>Email : <%= @student.email%>  </h4> 
<h4>Avatar :<%= image_tag @student.avatar %></h4>
<h4>Images :</h4>
<% @student.images.each do |image|%>
   <%= image_tag image %>
<%end %>
<%= download_pdf_path%>
<%= link_to  "download now " , "students#download_pdf" %>